USE funcionarios;

SELECT * FROM tabela_funcionarios;

UPDATE tabela_funcionarios SET COMISSAO = 0.05
WHERE MATRICULA = '12345';

SELECT * FROM tabela_funcionarios;

DROP TABLE tabela_funcionarios;

CREATE TABLE TABELA_FUNCIONARIOS2 (MATRICULA VARCHAR (5), NOME VARCHAR(100), COMISSAO FLOAT);

INSERT INTO tabela_funcionarios2 ( MATRICULA, NOME, COMISSAO) VALUES ('1234', 'ANDREA BOCCELI', 0.05);

SELECT* FROM tabela_funcionarios2;

INSERT INTO tabela_funcionarios2 (MATRICULA, NOME, COMISSAO) VALUES ('12345', 'LUCIANO PAVAROTTI', 0.1);

INSERT INTO tabela_funcionarios2 (MATRICULA, NOME, COMISSAO) VALUES ('54321', 'WOLFGANG AMADEUS MOZART', 0.1);

SELECT* FROM tabela_funcionarios2;

UPDATE tabela_funcionarios2 SET COMISSAO = 0.1
WHERE MATRICULA = '1234';

SELECT* FROM tabela_funcionarios2;

DROP TABLE tabela_funcionarios2;

CREATE TABLE TABELA_DOS_CONTRATADOS (MATRICULA VARCHAR(5), 
NOME VARCHAR(100), COMISSAO FLOAT, DATA_ADMISSAO DATE, DE_FERIAS BIT);

INSERT INTO tabela_dos_contratados (MATRICULA, NOME, COMISSAO, DATA_ADMISSAO, DE_FERIAS) VALUES ('1234', 'ANDREA BOCCELI', 0.1, '2023-01-19', 
0);

INSERT INTO tabela_dos_contratados (MATRICULA, NOME, COMISSAO, DATA_ADMISSAO, DE_FERIAS) VALUES ('12345', 'LUDWIG VAN BEETHOVEN', 0.1,
'2023-01-19', 0);


